package com.microdiab.mnotes.model;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Positive;


/**
 * Represents a patient note stored in the MongoDB database.
 * This class is mapped to the "collection_notes" collection in MongoDB
 * and is used to store and manage patient notes within the MicroDiab application.
 *
 * Each note is associated with a unique patient identifier ({@code patId})
 * that corresponds to the patient's record in the SQL database.
 * The note includes the patient's name and the note content itself.
 *
 * @see org.springframework.data.mongodb.core.mapping.Document
 */
@Document(collection = "collection_notes")
public class Note {

    /**
     * Unique identifier for the note, generated by MongoDB.
     * This field is mapped as a String for compatibility with ObjectId.
     */
    @Id
    private String id;

    /**
     * Patient identifier that corresponds to the patient's record in the SQL database.
     * Must be a positive number and cannot be null.
     */
    @NotNull(message = "patId cannot be null")
    @Positive(message = "patId must be a positive number")
    private Long patId;

    /**
     * Name of the patient associated with the note.
     * This field is mandatory and cannot be blank.
     */
    @NotBlank(message = "patient is mandatory")
    private String patient;

    /**
     * Content of the note.
     * This field supports multiline text and is mandatory.
     */
    @NotBlank(message = "note is mandatory")
    private String note;

    /**
     * Default constructor for the Note class.
     */
    public Note() {
    }

    /**
     * Parameterized constructor for the Note class.
     *
     * @param id      The unique identifier for the note.
     * @param patId   The patient identifier corresponding to the SQL database.
     * @param patient The name of the patient.
     * @param note    The content of the note.
     */
    public Note(String id, Long patId, String patient, String note) {
        this.id = id;
        this.patId = patId;
        this.patient = patient;
        this.note = note;
    }

    /**
     * Gets the unique identifier of the note.
     *
     * @return The unique identifier.
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the unique identifier of the note.
     *
     * @param id The unique identifier to set.
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Gets the patient identifier corresponding to the SQL database.
     *
     * @return The patient identifier.
     */
    public Long getPatId() {
        return patId;
    }

    /**
     * Sets the patient identifier corresponding to the SQL database.
     *
     * @param patId The patient identifier to set.
     */
    public void setPatId(Long patId) {
        this.patId = patId;
    }

    /**
     * Gets the name of the patient.
     *
     * @return The name of the patient.
     */
    public String getPatient() {
        return patient;
    }

    /**
     * Sets the name of the patient.
     *
     * @param patient The name of the patient to set.
     */
    public void setPatient(String patient) {
        this.patient = patient;
    }

    /**
     * Gets the content of the note.
     *
     * @return The content of the note.
     */
    public String getNote() {
        return note;
    }

    /**
     * Sets the content of the note.
     *
     * @param note The content of the note to set.
     */
    public void setNote(String note) {
        this.note = note;
    }

    /**
     * Returns a string representation of the note.
     * The string includes the patient identifier, patient name, and note content.
     *
     * @return A string representation of the note.
     */
    @Override
    public String toString() {
        return "Note{" +
                "patId=" + patId +
                ", patient='" + patient + '\'' +
                ", note='" + note + '\'' +
                '}';
    }
}
